allow commands to be executed while searchbox is in focus
ajaxorg/ace pull request #4699
Opened 2022-05-12 14:51 UTC by marmoure

*Issue #, if available:*
https://github.com/eXist-db/eXide/issues/113
*Description of changes:*
Allow keyboard commands to be executed even whilst the searchBox is in focus.
This can speed up the workflow a bit by avoiding the need for hitting `esc` then running the command,
the searchBox commands are the ones in priority and if the command doesn't belong to the searchBox it will fall to the editor handler.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

This open source contribution to the [ace](https://github.com/ajaxorg/ace) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2022-05-16 14:08 UTC, joewiz commented
Could a maintainer please approve the workflow so the CI check can proceed? We'd be happy to answer any questions or concerns about the PR, to aid in its review.

2022-05-16 14:14 UTC, andrewnester commented
@joewiz could you please describe a use-case why do you need this change?

2022-05-16 14:16 UTC, joewiz commented
@andrewnester Thank you! In our ace-based application, [eXide](https://exist-db.org/exist/apps/eXide) ([source](https://github.com/exist/eXide)), we found that when the keyboard focus is the Find pane (Edit > Find in Buffer), the keyboard shortcut for Save (File > Save) does not work. To save, you have to escape out of the Find pane, then save. So our goal is to be able to save the file even when the focus is in the Find pane.

2022-05-16 14:54 UTC, andrewnester requested changes
Could you add tests for this functionality?

2022-05-16 14:54 UTC, andrewnester commented
Thanks, generally the use case makes sense to me. @nightwing what do you think?

2022-05-23 22:00 UTC, joewiz commented
@andrewnester @nightwing Thank you both so much! We’re trying to assess the next step to take. Do you suggest that we add tests, or is there a more fundamental block behind pursuing the objective we set in this PR? We appreciate your advice.

2022-05-25 15:12 UTC, andrewnester commented
@joewiz test is definitely a must, but I guess one another fundamental point which @nightwing mentioned that the change you proposed only forwards commands to latest used keyboard handler. But there can be many of them https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/keyboard/keybinding.js#L62

The potential solution might be to explicitly define commands such as save and etc to be forwarded and working globally

For example, we can introduce new command property “global” which of set to true will allow command to be forwarded

What do you think @nightwing ?

2022-06-14 14:32 UTC, joewiz commented
@andrewnester @nightwing We are ready to proceed! We just need your advice about how you'd like us to do so - i.e., whether (a) to stick with the current approach of forwarding commands to the latest used keyboard handler or (b) to switch to using a new command property "global" facility which would allow designated commands such as ours to be forwarded? If the latter, ideally, this API would be made available for us to hook into, but if you're not able to provide this for us, could you advise us on where this change would need to be made so we could investigate whether it's feasible given our resources?

2022-06-15 13:47 UTC, andrewnester commented
@joewiz option B is definitely preferred one. But I guess you might use `editor. onCommandKey ` method which looks through the all registered handlers. It might be an easier solution, see our demo here: https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/demo/kitchen-sink/demo.js#L518

2022-06-29 13:09 UTC, adamretter commented
> curious what @nightwing thinks

@nightwing Can you comment on if you think the approach proposed by @andrewnester is the correct one please? (I work with @marmoure and @joewiz)

2022-08-25 20:23 UTC, nightwing commented
I like the idea with property global, it would help with prompt too, where f1 ctrl-f opens a searchbar in oneline editor.
But i am not sure how to implement it cleanly in such a way that would not require reimplementing most of callKeyboardHandlers 
 function in https://github.com/ajaxorg/ace/blob/master/src/keyboard/keybinding.js#L75

2023-10-31 18:56 UTC, closed without merging