Fix overflow button for long lines with one token
ajaxorg/ace pull request #4818
Opened 2022-06-02 19:30 UTC by Exaphis

*Issue #, if available:* #4817

*Description of changes:* Check if MAX_LINE_LENGTH is reached for the first token as well as the others.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-02 20:08 UTC, BenSouchet requested changes

2022-06-02 22:29 UTC, Exaphis commented on lib/ace/layer/text.js
>          for (var i = 1; i < tokens.length; i++) {
Thanks, replaced with your suggestion.

2022-06-03 07:46 UTC, Exaphis commented
Saw the build failed due to renderIndentGuide being passed a token instead of value. Also noticed that value should be updated with the result of renderIndentGuide, so I refactored it to use similar logic to renderWrappedLine.

2022-06-03 08:34 UTC, andrewnester approved these changes

2022-06-03 08:34 UTC, merged