Build script: fix CSS extract with `options.compress`
ajaxorg/ace pull request #4833
Opened 2022-07-03 19:39 UTC by arcanistzed

*Description of changes:*

During the build script, extract the CSS to the correct directory when `options.compress` is set to true. Otherwise, `readdirSync` on the next line will throw an error because the directory doesn't exist.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-04 09:56 UTC, andrewnester requested changes

2022-07-04 09:56 UTC, andrewnester commented on Makefile.dryice.js
> +    var dir = BUILD_DIR + "/src" + (options.compress ? "-min" : "") + (options.noconflict ? "-noconflict" : "");
it's better to reused `getTargetDir ` function here

2022-07-04 14:51 UTC, merged

2022-08-09 20:44 UTC, anthonyryan1 commented
This change has broken the generation of `css/ace.css`

This particularly affects deployments with `ace.config.set('useStrictCSP', true);` because they require all styles be specified in ace.css since they can't use any inline style attribute.

Here's a diff of the css file after this change: https://gist.github.com/anthonyryan1/11620290f2d82d4ff2b91948bebfb4d6

I don't think it was the intention to delete all the CSS from all the builds. This has caused display bugs in every release since 1.8.0.

2022-08-09 21:11 UTC, anthonyryan1 commented
The problem seems to stem from the fact that extractCSS uses a pretty simple set of regexes to find the CSS hiding in the JavaScript files.

These worked perfectly on the raw source code, but once we minify it, the regexes no longer work and fail to extract the CSS properly.

We either need to continue running extractCSS on non-minified javascript, or we need a better regex that can identify CSS in the already minified javascript.

2022-08-10 08:54 UTC, andrewnester commented
Reverted the change and released new fixed 1.9.5 version

2022-08-10 16:59 UTC, arcanistzed commented
That's unfortunate because now `options.compress` is broken again. Is the only solution to ship non-minified scripts?

2022-08-10 17:05 UTC, nightwing commented
@arcanistzed are you using ace-builds or building from ace repo?

2022-08-10 17:08 UTC, arcanistzed commented
I was building directly from the ace repo before https://github.com/arcanistzed/acelib/blob/330c8e01b797aaa55cfc1c213351a89e3c8b273c/.github/workflows/ace.yml
I'm going to try switching to ace-builds.

2022-08-10 17:58 UTC, andrewnester commented
if you need to unminified code you can install new `ace-code` npm package which contains Ace code

2022-08-16 20:31 UTC, nightwing commented
https://github.com/ajaxorg/ace/pull/4899 fixes the issue with compressed mode