Open valid url under cursor
ajaxorg/ace pull request #4970
Opened 2022-10-19 17:03 UTC by anijanyan

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-21 15:08 UTC, andrewnester requested changes

2022-10-21 15:08 UTC, andrewnester commented on src/editor.js
> +    this.findLinkAt = function (row,column) {
can we add a test for this function?

2022-10-21 15:08 UTC, andrewnester commented on src/editor.js
> +        var delta = column;
can we rename `delta` to `columnPosition` instead to reflect the intent?

2022-10-21 15:08 UTC, andrewnester commented on src/editor.js
> +            itLength = curLength + item.length;
can we rename curLength to previousPosition and itLength to currentPosition?

2022-10-21 15:08 UTC, andrewnester commented on src/editor.js
> +                    match = item.replace(/[\s:.,'";}\]]+$/, "");
should we add break here so we don't look at the rest of the line? it can help with large lines

2022-10-28 10:15 UTC, anijanyan commented
@andrewnester Thank you for review! All should be fixed now.

2022-10-28 14:37 UTC, andrewnester approved these changes

2022-10-28 14:38 UTC, andrewnester requested changes
Build fails with

> /home/runner/work/ace/ace/src/editor_commands_test.js
Warning:     8:5  warning  'ace' is assigned a value but never used          no-unused-vars
Warning:     9:5  warning  'EditSession' is assigned a value but never used  no-unused-vars
Error:   546:6  error    Unexpected trailing comma                         comma-dangle

> ✖ 3 problems (1 error, 2 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

2022-10-28 16:27 UTC, anijanyan commented
> Build fails with
> 
> > /home/runner/work/ace/ace/src/editor_commands_test.js
> > Warning:     8:5  warning  'ace' is assigned a value but never used          no-unused-vars
> > Warning:     9:5  warning  'EditSession' is assigned a value but never used  no-unused-vars
> > Error:   546:6  error    Unexpected trailing comma                         comma-dangle
> 
> > ✖ 3 problems (1 error, 2 warnings)
> > 1 error and 0 warnings potentially fixable with the `--fix` option.

Oh, sorry, haven't noticed this. Fixed now.

2022-10-29 10:45 UTC, merged